replicaCount: 2

image:
  repository: node
  tag: "20-alpine"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000
  nodePort: 30300

initContainer:
  enabled: true
  image: busybox:1.35

appConfig:
  dbHost: "mysql-svc"
  apiKey: "dev-secret-key-123"
  appPort: "3000"
  environment: "development"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi